name: parallel
dependencies:
  - python=3.11
  - r-base
  - r-essentials
  - r-languageserver
  - r-httpgd
  - pip
  - pip:
      - notebook
      - ipykernel
      - jupyter
      - numpy
      - pandas
      - matplotlib