name: parallel
dependencies:
  - python=3.11
  - r-base=4.3
  - r-essentials
  - r-languageserver
  - r-httpgd
  - pip
  - pip:
      - notebook
      - ipykernel
      - jupyter
      - numpy
      - pandas
      - matplotlib
      # Optional: For database (PostgreSQL) support
      - sqlalchemy
      - psycopg2-binary